all:
  vars:
    key_name: my_keypair
    instance_type: m1.small
    security_group: my_securitygroup
    image: ami-06cd52961ce9f0d85 # Amazon Linux AMI 2018.03 in Tokyo Region
    region: ap-northeast-1
launched:
  vars:
    ansible_user: ec2-user
    ansible_connection: ssh
    ansible_ssh_private_key_file: ./aws-private.pem
