- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: my_keypair
    instance_type: m1.small
    security_group: my_securitygroup
    image: ami-06cd52961ce9f0d85 # Amazon Linux AMI 2018.03 in Tokyo Region
    region: ap-northeast-1
  tasks:
    - name: create a new ec2 key pair
      ec2_key:
        name: "{{ key_name }}"
    - name: create a new security group
      ec2_group:
        name: "{{ security_group }}"
        description: To enable SSH
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         assign_public_ip: yes
      register: ec2
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"
    - name: Run benchmark
      hosts: launched
      become: True
      gather_facts: True
      tasks:
        - include_role:
            name: benchmark
    - name: Clean up instances, security group and key pair
      hosts: localhost
      connection: local
      tasks:
        - name: Terminate instances that were previously launched
          ec2:
            state: 'absent'
            instance_ids: '{{ ec2.instance_ids }}'
        - name: Delete security group
          ec2_group:
            group_id: "{{ security_group }}"
            state: absent
        - name: remove key pair by name
          ec2_key:
            name: my_keypair
            state: absent
